# Generated by Django 4.0.4 on 2022-04-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_bank', models.CharField(max_length=100, verbose_name='banco de origem')),
                ('origin_agency', models.CharField(max_length=4, verbose_name='agencia de origem')),
                ('origin_account', models.CharField(max_length=7, verbose_name='agencia de origem')),
                ('destination_bank', models.CharField(max_length=100, verbose_name='banco de origem')),
                ('destination_agency', models.CharField(max_length=4, verbose_name='agencia de origem')),
                ('destination_account', models.CharField(max_length=100, verbose_name='banco de origem')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('transaction_datetime', models.DateTimeField(verbose_name='Date e Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
