name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Copying configurations
      run: cp contrib/env-sample .env
    - name: Lint with flake8
      uses: py-actions/flake8@v2
    - name: Run Tests
      run: pytest --cov=cbe3
    - name: Posting Coverage
      run: codecov
